package org.common;

public enum Commands {
    SIGN_UP,
    SIGN_IN,
    SEARCH,
    HOMEPAGE_INFORMATION_LISTVIEW,
    GET_FOLLOWERS,
    GET_FOLLOWEE,
    GET_CONNECTION,
    POST_THIS,
    SHOW_MY_POSTS,
    DELETE_MY_POST,
    IS_ALREADY_LIKED,
    DELETE_LIKE,
    ADD_LIKE,
    EDIT_PROFILE,
}
