package org.common;

public enum Commands {
    SIGN_UP,
    SIGN_IN,
    SEARCH,
    HOMEPAGE_INFORMATION_LISTVIEW,
    GET_FOLLOWERS,
    GET_FOLLOWEE,
    GET_CONNECTION,
    POST_THIS,
    SHOW_MY_POSTS,
    SHOW_OTHERS_POSTS,
    DELETE_MY_POST,
    IS_ALREADY_LIKED,
    DELETE_LIKE,
    ADD_LIKE,
    SEE_LIKES_LIST,
    COMMENT_THIS,
    EDIT_PROFILE,
    SEE_COMMENTS_LIST,
    FIND_HASHTAG_MY_POSTS,
    FIND_HASHTAG_OTHERS_POSTS,
    DELETE_EDUCATION,
    GET_EDUCATIONS,
    GET_SKILLS,
    GET_CONTACT_INFO,
    SEARCH_MY_POSTS,
    SEARCH_OTHERS_POSTS

}
