package org.common;

public enum Response {
    FAILED_SIGNUP_INVALID_DATA,
    FAILED_SIGNUP_DATABASE_FAILURE,
    FAILED_SIGNUP_DUPLICATED_EMAIL,
    SUCCESSFUL_SIGNUP,
    FAILED_SIGN_IN_INVALID_DATA,
    FAILED_SIGN_IN_EMAIL_NOT_FOUND,
    FAILED_SIGN_IN_WRONG_PASSWORD,
    SUCCESSFUL_SIGN_IN,
}
